# Generated by Django 3.0.4 on 2020-03-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cellphone_no',
        ),
    ]
