# Generated by Django 3.0.4 on 2020-03-23 22:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50, verbose_name='shop name')),
                ('slug', models.SlugField(unique=True)),
                ('street_name', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('cellphone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('tel_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('description', models.TextField(max_length=300)),
                ('reg_no', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Registration number must be entered in the format: '0000/000000/00'. Up to 14 characters and digits allowed!", regex='^([\\d]){1,4}\\/(\\d){1,6}\\/(\\d){1,2}$')])),
                ('logo', models.ImageField(upload_to='images/shop/logo/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
