# Generated by Django 3.0.4 on 2020-04-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200405_1605'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='menu.Ingredient'),
        ),
    ]
